# Navigation links. The weight parameter defines the order of the links.

main:
  - name: About
    url: /#about
    weight: 10
  - name: Publications
    url: /#publications
    weight: 20
  - name: Projects
    url: /#projects
    weight: 30
  - name: Videos
    url: /#videos
    weight: 40
  - name: Blog
    url: blog/
    weight: 50
